version: 1
services:
  - type: web
    name: chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    healthCheckPath: /healthz
    region: oregon
